config/routes.rb
Rails.application.routes.draw do
  resources:factors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/factor.rb
class Factor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/factors_controller.rb
class FactorsController < ApplicationController

  def index
    @factor=Factor.all
  end
  def new
    @factor=Factor.new
  end

  def show
   @factor=Factor.find(params[:id])
   @address=@factor['address']
   @word=@factor['word']
   gon.address=@factor['address']
   gon.word=@factor['word']
  end

  def create
    if request.post?
      @factor=Factor.create(factor_params)
    end
    redirect_to @factor
  end

  def destroy
    factor=Factor.find(params[:id])
    factor.destroy
    redirect_to '/factors'
  end

end

  private

  def factor_params
    params.require(:factor).permit(:address, :word)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factors_helper.rb
module FactorsHelper
end

app/views/factors/index.html.erb
<table>
    <tr>
    <th>インデックス番号</th><th>起点住所</th><th>目的地</th><th>検索ワード</th>
    
    </tr>
    <%@factor.each do |factor|%>
    <tr>
        <td><%=factor.id%></td>
        <td><%=factor.address%></td>
        <td><%=factor.word%></td>
        <td><%=link_to 'show', factor_path(factor)%></td>
        <td><%= link_to 'Destroy' , factor , method: :delete,data: {confirm: 'Are you sure?' } %></td>
    </tr>
    <%end%>
</table>

<%= link_to 'プランを作る', 'factors/new'%>

app/views/factors/new.html.erb
<%= form_for(@factor,url:{controller:'factors',actions:'create'}) do |form|%>
    <div>
     <label for="address">Address</label>
     <%=form.text_field :address%>
    </div>

    <div>
    <label for="word">word</label>
    <%=form.text_field :word%>
   </div>

   <%=form.submit%>

   <%end%>

app/views/factors/show.html.erb
<div>
  
★結果★<br />
<div id="results" style="width: 100%; height: 200px; border: 1px dotted; padding: 10px; overflow-y: scroll;"></div>
</div>

<%= link_to '一覧へ戻る', '/factors'%>





<script type="text/javascript">
var placesList;

/*
 お店情報取得
*/
window.onload=function getPlaces(){
  
  //結果表示クリア
  document.getElementById("results").innerHTML = "";
  //placesList配列を初期化
  placesList = new Array();
  
  //入力した検索場所を取得
  var addressInput = gon.address;
  if (addressInput == "") {
    return;
  }
  
  //検索場所の位置情報を取得
  var geocoder = new google.maps.Geocoder();
  geocoder.geocode(
    {
      address: addressInput
    },
    function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        //取得した緯度・経度を使って周辺検索
        startNearbySearch(results[0].geometry.location);
      }
      else {
        alert(addressInput + "：位置情報が取得できませんでした。");
      }
    });
}

/*
 位置情報を使って周辺検索
  latLng : 位置座標（google.maps.LatLng）
*/
function startNearbySearch(latLng){
  
  //読み込み中表示
  document.getElementById("results").innerHTML = "Now Loading...";
  
  //Mapインスタンス生成
  var map = new google.maps.Map(
    document.createElement("div")
  );
  
  //PlacesServiceインスタンス生成
  var service = new google.maps.places.PlacesService(map);
  
  //入力したKeywordを取得
  var keywordInput = gon.word;
  
  //周辺検索
  service.nearbySearch(
    {
      location: latLng,
      radius: 5000,
      keyword: keywordInput,
      
    },
    displayResults
  );
}

/*
 周辺検索の結果表示
 ※nearbySearchのコールバック関数
  results : 検索結果
  status ： 実行結果ステータス
  pagination : ページネーション
*/
function displayResults(results, status, pagination) {
    
  if(status == google.maps.places.PlacesServiceStatus.OK) {
  
    //検索結果をplacesList配列に連結
    placesList = placesList.concat(results);
    
    //pagination.hasNextPage==trueの場合、
    //続きの検索結果あり
    if (pagination.hasNextPage) {
      
      //pagination.nextPageで次の検索結果を表示する
      //※連続実行すると取得に失敗するので、
      //1秒くらい間隔をおく
      setTimeout(pagination.nextPage(), 1000);
    
    //pagination.hasNextPage==falseになったら
    //全ての情報が取得できているので、
    //結果を表示する
    } else {
      
      //placesList配列をループして、
      //結果表示のHTMLタグを組み立てる
      var resultHTML = "<ol>";
      
      for (var i = 0; i < placesList.length; i++) {
        place = placesList[i];
        
        //ratingがないのものは「---」に表示変更
        var rating = place.rating;
        if(rating == undefined) rating = "---";
        
        //表示内容（評価＋名称）
        var content = "【" + rating + "】 " + place.name+place.vicinity;
        
        resultHTML += "<li>";
        resultHTML += content;
        resultHTML += "</li>";
      }
      
      resultHTML += "</ol>";
      
      //結果表示
      document.getElementById("results").innerHTML = resultHTML;
    }
  
  } else {
    //エラー表示
    var results = document.getElementById("results");
    if(status == google.maps.places.PlacesServiceStatus.ZERO_RESULTS) {
      results.innerHTML = "検索結果が0件です。";
    } else if(status == google.maps.places.PlacesServiceStatus.ERROR) {
      results.innerHTML = "サーバ接続に失敗しました。";
    } else if(status == google.maps.places.PlacesServiceStatus.INVALID_REQUEST) {
      results.innerHTML = "リクエストが無効でした。";
    } else if(status == google.maps.places.PlacesServiceStatus.OVER_QUERY_LIMIT) {
      results.innerHTML = "リクエストの利用制限回数を超えました。";
    } else if(status == google.maps.places.PlacesServiceStatus.REQUEST_DENIED) {
      results.innerHTML = "サービスが使えない状態でした。";
    } else if(status == google.maps.places.PlacesServiceStatus.UNKNOWN_ERROR) {
      results.innerHTML = "原因不明のエラーが発生しました。";
    }

  }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Google</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <%= include_gon %>
  </head>

  <body>
    <%= yield %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDJzux1JhQNtBO-9TNu2fNp2hzzJOcyln8&libraries=places"></script>

  </body>
</html>
s